ESW-519
myantandco/fw_skiin_standalone_algorithms pull request #1
Opened 2024-05-27 15:45 UTC by glor-w

# Summary
Match fw implementation to python implementation. Update latch function to keep a static array (one variable for each channel). Multiply ecg_filter with filter softness instead of latch to create model input. Change all double variables to floats and update filter coefficients to reflect this. Add .clang formatting. Added csv_writers.h

# Added
'csv_writers.c' and 'csv_writers.h' - to help read and write data from csv files
'config.h' - to set which files/folders to read and write from
'.clang-format' - contains formatting rules

# Changed
'.gitignore' - ignore vscode and example data folders as well
'MakeFile' - add csv_writers.c to sources and make build dependent on config.h, update CC and CXX locations
'main.c' - change GARMENT_ID_DEFUALT to CHEST_BAND, read data from csv from config.h instead of from input.h, output ble data to csv, pass input data directly to buffer for abr preprocessing and running model, do not need to put into 24 sample buffer, add ABR_INPUT_BASELINE_VALUE to input since it gets subtracted in preprocessing.c, run abr_pp_get_rpeak only once (instead of 3x - once per channel). write algo_output and ble outputs to csv. make buffer a float instead of double. conform to clang-format
'abr_postprocess.c and abr_postprocess.h' - conform to clang-format
'abr_preprocess.c' - replace doubles with floats, change filter coefficients from double to float (cut all at 7 decimals), update latch_sigmoid() to have ecg_id as an input,  update latch_q in latch_sigmoid() to be a static array which holds one latch value per channel, in get_preprocess_out() step (6) multiply filtered_ecg with quality_info[ecg_id].filter_softness instead of .latch to match design, write intermediate values to csvs, conform to clang-format
'abr_preprocess.h' - conform to clang-format
'data_processing.c and data_processing.h' - change doubles to floats, conform to clang-format
'ecg_algo.cpp and ecg_algo.h' - change doubles to floats, move ABR_INPUT_BASELINE_VALUE from .cpp to .h file so it can be accessed by main.c

# Removed
- N/A

# Testing
- 5 example trials were tested to compare between python and c outputs to ensure they match, report in RDR510 ABR fw standalone evaluation

# Automated Testing (Currently Not Used)
- N/A

2024-05-27 17:57 UTC, rhirani-myant requested changes
@glor-w  Please discuss with me on how to implement the changes requested.

2024-05-27 17:57 UTC, rhirani-myant commented on abr_algo_standalone/myant/abr_preprocess.c
> +    write_csv_single("q6_filtersoft.csv", *filter_softness, ecg_id);
Same as above.

2024-05-27 17:57 UTC, rhirani-myant commented on abr_algo_standalone/myant/abr_preprocess.c
> +    write_csv_single("q7_qclass.csv", quality_class_temp, ecg_id);
Same as above

2024-05-27 17:57 UTC, rhirani-myant commented on abr_algo_standalone/myant/abr_preprocess.c
> +    write_csv_single("q8_noisedetect.csv", (int)*noise_detect, ecg_id);
Same as above

2024-05-27 17:57 UTC, rhirani-myant commented on abr_algo_standalone/myant/abr_preprocess.c
> +    write_csv_single("e1_notch.csv", temp_ecg[ecg_ch], ecg_ch);
Same as above

2024-05-27 17:57 UTC, rhirani-myant commented on abr_algo_standalone/myant/abr_preprocess.c
> +    write_csv_single("e3_filtxlatch.csv", processed_ecg[ecg_ch], ecg_ch);
Same as above

2024-05-27 18:16 UTC, toastwmy requested changes

2024-05-27 18:18 UTC, toastwmy commented
We use [this coding style document.](https://docs.google.com/document/d/1CwgT6e7RqLKq2x9Tkgk1Hfi_QcEEWAAyIE32ykQolyA) Not saying that this repo should necessarily follow it as it is shared between FW and DS, but consistency would be good in the repository.

2024-05-27 19:13 UTC, toastwmy commented on abr_algo_standalone/Makefile
> +$(BUILDDIR)/$(MAIN_BIN) : $(SRCS) config.h
Instead of the entire list of includes in `CXXFLAGS`, it would be better if those were broken off into includes. Then we can say the list of include files is every header file in that list of directories and ask it to recompile if any of those change in the build rules as well.

2024-05-30 14:05 UTC, glor-w commented on abr_algo_standalone/Makefile
> +$(BUILDDIR)/$(MAIN_BIN) : $(SRCS) config.h
not sure what this means, I removed config.h. @rhirani-myant can you handle this?

2024-05-30 14:06 UTC, glor-w commented on abr_algo_standalone/myant/csv_writers.h
> +void createFolderIfNotExists(const char *folderName);
done and used camel case

2024-05-30 14:06 UTC, glor-w commented on abr_algo_standalone/myant/csv_writers.c
> +void read_csv(const char *filename, float input_ch1[], float input_ch2[], float input_ch3[], int *num_rows)
returned -errno if error otherwise return 0 for these functions

2024-05-30 14:07 UTC, glor-w commented on abr_algo_standalone/myant/ecg_algo.h
> +#define ABR_INPUT_BASELINE_VALUE        685.7142857142857l
changed to float 685.7142857f

2024-05-30 14:07 UTC, glor-w commented on abr_algo_standalone/config.h
> +#ifndef CONFIG_H
moved all to csv_writers.h and removed config.h from repo

2024-05-30 14:07 UTC, glor-w commented on abr_algo_standalone/Makefile
> +
reverted

2024-05-30 14:07 UTC, glor-w commented on .gitignore
> +/example_data/*
fixed

2024-05-30 14:08 UTC, glor-w commented on abr_algo_standalone/myant/ecg_algo.h
> +#define ABR_INPUT_BASELINE_VALUE        685.7142857142857l
fixed

2024-05-30 15:45 UTC, glor-w commented on abr_algo_standalone/myant/csv_writers.h
> +#include "config.h"
fixed

2024-05-30 15:45 UTC, glor-w commented on abr_algo_standalone/myant/csv_writers.c
> +    char filePath[200];    // Adjust the size according to your need
fixed

2024-05-30 15:46 UTC, glor-w commented on abr_algo_standalone/myant/csv_writers.c
> +    char filePath[200];    // Adjust the size according to your need
fixed, called it MAX_PATH_LEN

2024-05-30 15:46 UTC, glor-w commented on abr_algo_standalone/myant/csv_writers.c
> +    char filePath[200];    // Adjust the size according to your need
fixed, called it MAX_PATH_LEN

2024-05-30 15:46 UTC, glor-w commented on abr_algo_standalone/myant/csv_writers.c
> +    char line[1024];
fixed, called it MAX_LINE_LEN

2024-05-30 15:46 UTC, glor-w commented on abr_algo_standalone/myant/csv_writers.c
> +#include <stdbool.h>
checked, left comments on what is being used from includes

2024-05-30 15:47 UTC, glor-w commented on abr_algo_standalone/main.c
> +#define GARMENT_ID_DEFAULT \
fixed

2024-05-30 15:47 UTC, glor-w commented on abr_algo_standalone/main.c
> +    float input_ch1[MAX_ROWS];
moved

2024-05-30 15:47 UTC, glor-w commented on abr_algo_standalone/main.c
> +        write_csv_single("e4_pred.csv", algo_output[0], 2);
added comments to this and next section

2024-05-30 15:47 UTC, glor-w commented on abr_algo_standalone/main.c
> +                // printf("Sample[%d] ECG Channel %d: rpeak_max = %d rpeak_index
deleted

2024-05-30 15:48 UTC, glor-w commented on abr_algo_standalone/main.c
> +    uint8_t       rpeak_max   = 0;
renamed to camel case and added tags

2024-05-30 15:48 UTC, glor-w commented on abr_algo_standalone/myant/abr_preprocess.c
> +    write_csv_single("q1_point5filt.csv", temp_quality[ecg_id], ecg_id);
@rhirani-myant  to fix this and below

2024-05-30 15:56 UTC, glor-w commented on abr_algo_standalone/myant/abr_postprocess.c
> +#define ABR_RPEAK_RANGE          4.7f     // changes based on garment
ABR_RPEAK_Range and ABR_RPEAK_THRESHOLD_MIN need to change based on garment id
chest ABR_RPEAK_THRESHOLD_MIN = -1.7
udw ABR_RPEAK_THRESHOLD_MIN = -1.8

ABR_RPEAK_RANGE = 3.0 - ABR_RPEAK_THRESHOLD_MIN

@rhirani-myant  to fix

2024-06-03 19:49 UTC, rhirani-myant approved these changes
@glor-w Finished the changes, looks ready to merge on my end

2024-06-04 16:41 UTC, toastwmy approved these changes
Looks good to me!

2024-06-04 16:41 UTC, merged