[ESW-519] ABR 2.0 Algorithm Fixes Part 2 (rpeak resolution and latch limits)
myantandco/fw_skiin_standalone_algorithms pull request #2
Opened 2024-06-04 19:58 UTC by glor-w

# Summary
Match fw implementation to python implementation. Fix ABR_RPEAK_RESOLUTION to be 30 bits not 31. Set latch limits based on garment type.

# Added
None

# Changed
'abr_postprocess.c' - changed ABR_RPEAK_RESOLUTION to be 30 not 31
'abr_preprocess.c' - added different latch limits per garment id
'abr_preprocess.h' - added function definition to set latch limits based on garment id
'ecg_algo.cpp' - call ABRPreProcess_SetLatchLimits when garment id is set

# Removed
- N/A

# Testing
- 8 example trials were tested to compare between python and c outputs to ensure they match, report in RDR510 ABR fw standalone evaluation
- 5 trials of chest data
- 3 trials of underwear data

# Automated Testing (Currently Not Used)
- N/A

2024-06-05 14:19 UTC, rhirani-myant requested changes
Minimal changes requested. Please update and we can merge relatively quickly.

2024-06-05 14:19 UTC, rhirani-myant commented on abr_algo_standalone/myant/abr_preprocess.c
> +static float     dLatchLimitLow  = 0.0f;
I think these should just be moved up to be with the other global variables. Seems oddly placed in the middle of functions.

2024-06-05 14:19 UTC, rhirani-myant commented on abr_algo_standalone/myant/abr_postprocess.c
> +#define ABR_RPEAK_RESOLUTION          30.0f    // 31 bits, 0 is no rpeak, so 30 bits
Are these kinds of values are captured in the ALDD for the ABR 2.0 algorithm?

2024-06-05 14:54 UTC, glor-w commented on abr_algo_standalone/myant/abr_postprocess.c
> +#define ABR_RPEAK_RESOLUTION          30.0f    // 31 bits, 0 is no rpeak, so 30 bits
now it is a bit more clear (previously I used words to say 1-31, but now I actually put a defined constant there).
section 6.3
https://docs.google.com/document/d/1VK6elQ9Boa94P1pPA48IAMBv22rGrBKG/edit

2024-06-05 14:54 UTC, glor-w commented on abr_algo_standalone/myant/abr_preprocess.c
> +static float     dLatchLimitLow  = 0.0f;
fixed

2024-06-06 12:31 UTC, rhirani-myant approved these changes

2024-06-07 19:58 UTC, merged