[ESW-581] ECG Bit Reduction Standalone Algorithm
myantandco/fw_skiin_standalone_algorithms pull request #3
Opened 2024-06-11 18:25 UTC by rhirani-myant

2024-06-11 18:35 UTC, rhirani-myant commented on ecg_bit_reduction/main.c
> +        ecg_reduced_data = ecgbr_sample_reduction((uint32_t)dpInput[i], ECG1, ecg_buffer_refresh);
Not sure what the point of `ecg_buffer_refresh` is. Looking into it

2024-06-11 18:47 UTC, rhirani-myant commented on ecg_bit_reduction/main.c
> +        ecg_reduced_data = ecgbr_sample_reduction((uint32_t)dpInput[i], ECG1, ecg_buffer_refresh);
Resolved; `ecg_buffer_refresh` is only true for the first iteration on boot, set to false afterwards

2024-06-14 18:35 UTC, toastwmy requested changes
Functionally looks good, will approve and merge when code style is changed.

2024-06-14 18:35 UTC, toastwmy commented on ecg_bit_reduction/ecg_bit_reduction.c
> +static bool check_restart_filter( uint32_t raw_sample, ecg_sens_id ecg_id, bool restart)
Naming convention again (variable names)

2024-06-14 18:35 UTC, toastwmy commented on ecg_bit_reduction/ecg_bit_reduction.c
> +    static uint8_t sample_count[MAX_ECG] = {0};
Declaring static arrays in a function isn't bad as long as they're const length; however, we've run into memleaks before when a static array was declared with a variable - perhaps move them out and into a context struct.

2024-06-14 18:35 UTC, toastwmy commented on ecg_bit_reduction/ecg_bit_reduction.c
> +static bool check_restart_filter( uint32_t raw_sample, ecg_sens_id ecg_id, bool restart)
This repeats several times below as well.

2024-06-17 16:17 UTC, toastwmy approved these changes
LGTM!

2024-06-17 16:17 UTC, merged