[ESW-591][Gen 1.1] Integrate Updated Bit Reduction Implementation
myantandco/fw_skiin_standalone_algorithms pull request #4
Opened 2024-06-28 20:03 UTC by glor-w

# Summary
Update filter to floats. Match fw implementation to python implementation. Fixed check reset logic. Removed ecgbr_digital_filter (which used doubles).

# Added
- Indicate what new files/function were added within this PR
- For example: `antialias.c` - Contains algorithms relevant for down sampling ECG data
N/A

# Changed
- Indicate what files/function were changed within this PR
- Provide a brief explanation of what changed in each file
- For example: `afe4960p.c` - Modified how register settings are applied for setting ECG Ch 1 and Ch 2 Pin Mappings
- ecg_bit_reduction.c - changed all doubles to floats. used floorf instead of floor. Call digital_filter instead of ecgbr_digital_filter. Updated CheckRestartFilter logic and renamed some variables to clarify purpose and match with python implementation. Add cap to samples_since_last_high. Rename some thresholds to match python.
- main.c - bECGReducedData should be int16_t not uint16_t, clarify when fECGBufferRefresh should be used. Add printouts for all three channels.
- data_processing.c and .h- removed ecgbr_digital_filter

# Removed
- N/A

# Testing
- a 0.17hz rectangular pulse wave (recored using whaleteq and skiin) was used tested to show that the frequency response of the c filter was acceptable
- example of skiin data BR2_in1_PACE_ID0465_20211004_3ECG_underwear_LyingDown was checked to ensure three channels of ecg matched between python and c
- example of noisy data skiin data was also tested to check that reset occurs at the same time between python and c: BR1_in1_orignial_filtered_processed_1.csv (only one channel), but the logic applies to all three channels.

# Automated Testing (Currently Not Used)
- N/A

2024-06-28 20:43 UTC, rhirani-myant requested changes
Minor formatting requests to support consistency + faster integration. Otherwise, great work! Looks much better.

2024-06-28 20:43 UTC, rhirani-myant commented on shared/data_processing.c
> +#include "csv_writers.h"
Let's remove this since its not being used anymore.

2024-06-28 20:43 UTC, rhirani-myant commented on shared/data_processing.c
> +            pIn[i] = dInitialSample;    // Initialize input buffer with initial
For in-line comments, I personally let them run past the line limit but not sure how to adjust the clang to support this. As long as it's consistent though, it doesn't really matter

2024-06-28 20:43 UTC, rhirani-myant commented on shared/data_processing.h
>  #include <string.h>
Does this file need <stdbool.h> since the fReset argument is boolean type?

2024-06-28 20:43 UTC, rhirani-myant commented on ecg_bit_reduction/main.c
> +    bool fECGBufferRefresh = true;    // apply whenever pod is reset, or there
Single line comment?

2024-06-28 20:45 UTC, toastwmy approved these changes
Looks good. Style is perfect. Had some thoughts about using assignment operators, and whether that is clear or not, but I think that's a different discussion.

2024-06-28 20:45 UTC, toastwmy commented on shared/data_processing.c
> +    tmp                    /= pA[0];
I'm wondering if we should start using `tmp = tmp/pA[0];` for readability so we don't miss the `/=`. Just a thought.

2024-06-28 20:46 UTC, toastwmy commented on shared/data_processing.c
> +            pIn[i] = dInitialSample;    // Initialize input buffer with initial
Yeah, I prefer to not use in-line comments and have them always be `/* ...comment... */` to be clear about where it ends

2024-06-28 20:47 UTC, rhirani-myant commented on shared/data_processing.c
> +    tmp                    /= pA[0];
Agreed. Would be more explicitly clear.

2024-07-02 15:21 UTC, glor-w commented on shared/data_processing.h
>  #include <string.h>
hmm I think it already has stdbool in both .c and .h?

2024-07-02 15:25 UTC, glor-w commented on shared/data_processing.c
> +#include "csv_writers.h"
removed

2024-07-02 15:25 UTC, glor-w commented on shared/data_processing.c
> +            pIn[i] = dInitialSample;    // Initialize input buffer with initial
fixed for all comments except after #defines

2024-07-02 15:25 UTC, glor-w commented on ecg_bit_reduction/main.c
> +    bool fECGBufferRefresh = true;    // apply whenever pod is reset, or there
fixed

2024-07-02 15:25 UTC, glor-w commented on shared/data_processing.c
> +    tmp                    /= pA[0];
changed

2024-07-02 15:44 UTC, rhirani-myant approved these changes

2024-07-02 15:44 UTC, merged